/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_ZMQException */

#ifndef _Included_org_zeromq_ZMQException
#define _Included_org_zeromq_ZMQException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_zeromq_ZMQException_serialVersionUID
#define org_zeromq_ZMQException_serialVersionUID -3042686055658047285i64
#undef org_zeromq_ZMQException_serialVersionUID
#define org_zeromq_ZMQException_serialVersionUID -3387516993124229948i64
#undef org_zeromq_ZMQException_serialVersionUID
#define org_zeromq_ZMQException_serialVersionUID -7034897190745766939i64
#undef org_zeromq_ZMQException_serialVersionUID
#define org_zeromq_ZMQException_serialVersionUID -978820750094924644i64
#ifdef __cplusplus
}
#endif
#endif
