/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_EmbeddedLibraryTools */

#ifndef _Included_org_zeromq_EmbeddedLibraryTools
#define _Included_org_zeromq_EmbeddedLibraryTools
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
